###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    redis:
      image: redis:alpine
      container_name: steam-redis

    mysql:
      restart: always
      image: mysql:8.0
      container_name: steam-mysql
      working_dir: /application
      command: ['--default-authentication-plugin=mysql_native_password']
      volumes:
        - .:/application
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=steam
        - MYSQL_DATABASE=steam
        - MYSQL_USER=steam
        - MYSQL_PASSWORD=steam

    webserver:
      restart: always
      image: nginx:alpine
      container_name: steam-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
      links:
       - "php-fpm:php-fpm"

    php-fpm:
      restart: always
      build: phpdocker/php-fpm
      container_name: steam-php-fpm
      working_dir: /application
      ports:
      - "9000:9000"
      volumes:
        - .:/application

    supervisor:
      restart: always
      build: phpdocker/supervisor
      container_name: steam-supervisor
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/supervisor/crontab:/etc/cron.d/cron
        - ./phpdocker/supervisor/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

